### ISSUE TITLE
A problem when enrolling 

### ISSUE THREAD

**Issue by Jhhhha** [YanB25/Waterfall-frontend#4]
This is my second time waiting for the check when enrolling!!!
<img width="639" alt="屏幕快照 2019-06-01 18 09 37" src="https://user-images.githubusercontent.com/24792965/58747066-712a3e00-8498-11e9-982b-ad935ba18dbc.png">

**Comment by Jhhhha** [comment]
This problem happens from time to time, not always.

**Comment by YanB25** [comment]
That's a strange one, because I never meet the problem before.
@gtbl2012

**Comment by YanB25** [comment]
That's quite an interesting bugs.
As the code
https://github.com/YanB25/Waterfall-frontend/blob/91495d76e4ffa23b75f4a3e8c5d3b7ec9b9a15ac/src/components/topbar/SignUp.vue#L21
if I use `v-model.number="xxx"`, the `element UI` will try to parse the field as number and stuck.
